### ISSUE TITLE
Ambiguous KAF and KAF WITH DOT ABOVE

### ISSUE THREAD

**Issue by fikr4n** [alif-type/amiri#84]
السلام عليكم

There is some case where letter KAF/KEHEH + NOON and KAF/KEHEH WITH DOT ABOVE + ALEF MAKSURA look different but alike:

ڬىل = ڬ ى ل
كنل = ك ن ل
ݢىل = ݢ ى ل
کنل = ک ن ل

Here is the screenshot:

![screenshot from 2016-06-13 21-45-04](https://cloud.githubusercontent.com/assets/5564999/16011579/4e55b82a-31b0-11e6-9c41-5859057f24de.png)

**Comment by khaledhosny** [comment]
What language uses such combination? If it is really ambiguous for native readers (I think it is not, but I’m not a native reader) we can disable this form for that particular language (or set of languages).

**Comment by fikr4n** [comment]
KAF/KEHEH WITH DOT ABOVE is used in Jawi alphabet, sometimes called Old
Malay. It is official script in Brunei and Malaysia, and also used in
Indonesia (but not official). I forgot what word I typed so that I found
it, might be "كنال" (kenal, عربية: عرف, English: know) -- someone please
correct me. Moreover I am not Brunei nor Malaysian so I don't know exactly
if that spelling really exists in the dictionary; I mean "kenal" does exist
but I don't know the exact spelling in Jawi.

On Mon, Jun 13, 2016 at 11:26 PM, Khaled Hosny <notifications@github.com>
wrote:

> What language uses such combination? If it is really ambiguous for native
> readers (I think it is not, but I’m not a native reader) we can disable
> this form for that particular language (or set of languages).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/khaledhosny/amiri-font/issues/84#issuecomment-225633761>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFTqR2oUuBI2-4HS7hZ0cK066DfrQx_Lks5qLYS6gaJpZM4I0aKy>
> .
>



-- 
general <fikr4n@gmail.com> | academic <fikrul.arif@alumni.ui.ac.id> | work
<fikrul.nadra@id.ey.com>
public key
<http://keyserver.ubuntu.com/pks/lookup?op=index&search=fikr4n%40gmail.com&fingerprint=on&exact=on>

**Comment by fikr4n** [comment]
I am sorry for lack of example. These are they:
كنال (kenal, English: know)
ݢىلاڤ (gelap, English: dark)

However they could also be كىنال and ݢلاڤ. I don't know the correct
spelling.

On Thu, Jun 16, 2016 at 3:47 AM, Fikrul Arif <fikr4n@gmail.com> wrote:

> KAF/KEHEH WITH DOT ABOVE is used in Jawi alphabet, sometimes called Old
> Malay. It is official script in Brunei and Malaysia, and also used in
> Indonesia (but not official). I forgot what word I typed so that I found
> it, might be "كنال" (kenal, عربية: عرف, English: know) -- someone please
> correct me. Moreover I am not Brunei nor Malaysian so I don't know exactly
> if that spelling really exists in the dictionary; I mean "kenal" does exist
> but I don't know the exact spelling in Jawi.
>
> On Mon, Jun 13, 2016 at 11:26 PM, Khaled Hosny <notifications@github.com>
> wrote:
>
>> What language uses such combination? If it is really ambiguous for native
>> readers (I think it is not, but I’m not a native reader) we can disable
>> this form for that particular language (or set of languages).
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/khaledhosny/amiri-font/issues/84#issuecomment-225633761>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AFTqR2oUuBI2-4HS7hZ0cK066DfrQx_Lks5qLYS6gaJpZM4I0aKy>
>> .
>>
>
>
>
> --
> general <fikr4n@gmail.com> | academic <fikrul.arif@alumni.ui.ac.id> | work
> <fikrul.nadra@id.ey.com>
> public key
> <http://keyserver.ubuntu.com/pks/lookup?op=index&search=fikr4n%40gmail.com&fingerprint=on&exact=on>
>



-- 
general <fikr4n@gmail.com> | academic <fikrul.arif@alumni.ui.ac.id> | work
<fikrul.nadra@id.ey.com>
public key
<http://keyserver.ubuntu.com/pks/lookup?op=index&search=fikr4n%40gmail.com&fingerprint=on&exact=on>

**Comment by khaledhosny** [comment]
I think we will have to live with that ambiguity until a native Jawi user complains.

**Comment by MuhdNurHidayat** [comment]
> I am sorry for lack of example. These are they:
> كنال (kenal, English: know)
> ݢىلاڤ (gelap, English: dark)
> 
> However they could also be كىنال and ݢلاڤ. I don't know the correct
> spelling.

The word 'kenal' is spelt as کنل and 'gelap' is spelt as ݢلڤ based on the (Malaysian) Rumi-Jawi Spelling Registry (Daftar Ejaan Rumi-Jawi) released by [Dewan Bahasa dan Pustaka](https://en.wikipedia.org/wiki/Dewan_Bahasa_dan_Pustaka), the government body responsible for coordinating the use of the Malay language and Malay-language literature in Malaysia. (Rumi is the Malay name for "romanized Malay" in Latin script)

The Jawi spelling is also written on both of those words' registry in Malay Dictionary (Kamus Bahasa Melayu) on Malay Writing Reference Centre (Pusat Rujukan Persuratan Melayu / PRPM) portal, which is usually used for all Malay language related works in Malaysia including legal advice.
http://prpm.dbp.gov.my/Cari1?keyword=kenal
http://prpm.dbp.gov.my/Cari1?keyword=gelap
![image](https://user-images.githubusercontent.com/12217018/69567789-2af00a80-0ff5-11ea-99d3-63008c278ab3.png) ![image](https://user-images.githubusercontent.com/12217018/69567764-190e6780-0ff5-11ea-8c43-65a93dc01e11.png)

Also, كىنال by itself would be very wrong spelling, as ى in Malay is only used to represent the ə sound at the end of word... If it's in middle or at start, it will be spelt as ا instead, so that would be كانال ... but even so, when there's two ا separated by consonant then the first one will be dropped and it will become كنال and after that you need to consider another rule where an ا in between two consonants of one syllable should be dropped so it goes back to کنل just as the spelling in the official registry

the way you put the sample was like you're literally substituting the Rumi spelling with the Jawi spelling, it doesn't work that way, in fact some word can be spelt differently in Jawi despite same spelling on Rumi... famous example would be "perang":
```
| Rumi spelling | Reading  | Jawi spelling | Meaning |
|    perang     | /pə.raŋ/ |       ڤرڠ     |   war   |
|    perang     | /pe.raŋ/ |      ڤيرڠ     |  brown  |
```
there are also unofficial tools to convert Rumi to Jawi specific for Malay language but we will usually refer to the official entries on PRPM for confirmation as those tools were not reliable
